# Generated by Django 5.1.6 on 2025-02-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('feliz', '😊 Feliz'), ('agradecido', '🙏 Agradecido'), ('emocionado', '🤩 Emocionado'), ('triste', '😢 Triste'), ('enojado', '😠 Enojado'), ('relajado', '😌 Relajado'), ('contento', '😃 Contento'), ('cansado', '😫 Cansado'), ('aburrido', '😒 Aburrido')], max_length=20)),
                ('description_day', models.TextField(blank=True, verbose_name='Cuéntame cómo fue tu día')),
                ('discovery', models.TextField(blank=True, verbose_name='¿Descubriste algo nuevo hoy?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Registro Emocional',
                'verbose_name_plural': 'Registros Emocionales',
                'ordering': ['-created_date'],
            },
        ),
    ]
