# Generated by Django 5.1.6 on 2025-05-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording_emotion', '0005_alter_recordingemotion_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingemotion',
            name='emotion',
            field=models.CharField(choices=[('feliz', '😊 Feliz'), ('agradecido', '🙏 Agradecido'), ('emocionado', '🤩 Emocionado'), ('relajado', '😌 Relajado'), ('normal', '🙂 Normal'), ('contento', '😃 Contento'), ('triste', '😢 Triste'), ('enojado', '😠 Enojado'), ('cansado', '😫 Cansado'), ('aburrido', '😒 Aburrido')], max_length=20),
        ),
    ]
