# Generated by Django 5.1.6 on 2025-05-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_registers_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swotanalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Análisis DOFA', 'verbose_name_plural': 'Análisis DOFA'},
        ),
        migrations.AddField(
            model_name='swotanalysis',
            name='processed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
