# Generated by Django 5.1.6 on 2025-05-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_registers_ai', '0002_alter_swotanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swotanalysis',
            name='analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='swotanalysis',
            name='negative_patterns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='swotanalysis',
            name='positive_patterns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='swotanalysis',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
    ]
