# Generated by Django 5.1.6 on 2025-04-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_ideas', '0002_addnewideas_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewideas',
            name='idea',
            field=models.TextField(verbose_name='¿Cuál es tu idea?'),
        ),
    ]
