# Generated by Django 5.1.6 on 2025-04-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_ideas', '0003_alter_addnewideas_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewideas',
            name='idea',
            field=models.TextField(blank=True, verbose_name='¿Cuál es tu idea?'),
        ),
        migrations.AlterField(
            model_name='addnewideas',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
